### ISSUE TITLE
API KEY storage

### ISSUE THREAD

**Issue by hippyau** [NishantJoshi00/codex-autocomplete#1]
Hi,  cool extension!

Where in setting can the API KEY be put?

**Comment by NishantJoshi00** [comment]
Hello @hippyau,
Glad you are interested in it. The *Codex: Change Codex API Key* From the command palette would do the trick.
Other wise once you restart your PC the key is automatically removed and will be asked of you, while starting a new session

**Comment by hippyau** [comment]
Thank you for this, it's a very cool extension!   I just with the API key could be saved?
