### ISSUE TITLE
Verifying the API key

### ISSUE THREAD

**Issue by jvz-devx** [NishantJoshi00/codex-autocomplete#2]
I cant get further then Verifying the API key, i enter the api key and then nothing happens.

**Comment by gabenitez** [comment]
After some debugging got to reproduce this too... seems that openai's certificate is invalid, and plugin is not able to make requests. I've sent a pull request, but as my fix is insecure is completely understandable if it's not merged. Anyways, if you are as anxious as I am, you can pull this version https://github.com/solunika/codex-autocomplete/tree/fix/CertificateIsInvalidOverride

**Comment by NishantJoshi00** [comment]
Thank you for pointing this out, I will make sure to look at the pull request. I am a bit conscious about the security tho, so I will check the certificate issue, with openai's API, one last time

**Comment by NishantJoshi00** [comment]
I have patched the current version of the extension with the fix suggested by @gabenitez, but I would like to warn you that this fix is vulnerable as we are disabling the server certificate checks, and I would try to make it more secure as soon as possible, in the next patches, please suggest if you have any solution. Thank you!
