### ISSUE TITLE
Select other models (e.g., text-davinci-002)

### ISSUE THREAD

**Issue by albert-ying** [NishantJoshi00/codex-autocomplete#6]
Hi, since the openAI has other models for text generation, is it possible to allow users to select other models using this extension? This will be especially helpful for people who write markdown files or LaTeX documents in VScode.

Is this something easy to implement on top of the current extension?

Thank you!

**Comment by NishantJoshi00** [comment]
Hello @albert-ying,
Thanks for pointing that out, I was also thinking about implementing this in the extension. Due to a delay in the schedule however, I push something soon addressing this concern in this week.
Thank you!

**Comment by albert-ying** [comment]
Ok, I kind of implemented that by modifying the `path` to `/v1/engines/text-davinci-002/completions` in the `extension.js`. 

However, I don't know `.js` language myself... Could you help me a little bit on how to add the setting to limit the number of words it is used for the query -- since the text-davinci model is charging based on number of token (for example, usually last 500 words from cursor is sufficient for generating a reasonable response)?

p.s., It is also a good feature for code completion anyway since you don't want to be stucked forever when you have a huge code file.

Good to hear that you are also interested in this!

**Comment by albert-ying** [comment]
This is what I currently got from this hack. I wrote the first line and ran the `Generate Code Compeletion`
<img width="1854" alt="image" src="https://user-images.githubusercontent.com/59846322/167783581-c2364b2a-70da-4385-bb3c-2a7f07fc98ab.png">

This is a little bit annoying that each time I do a new prediction based on last one, it adds a empty line -- does this also happening for code completion?

**Comment by NishantJoshi00** [comment]
Thank you for waiting, I have updated the internal text selection method. Here, you can use text selection to specify which text you want to send to the API. I hope this addresses your issue. If no text is selected, the entire document is used for reference
[extension.ts 🔗](https://github.com/NishantJoshi00/codex-autocomplete/blob/e68826ab49d508de62ed121af1c98a0ac4aa76c3/src/extension.ts#L85)
